version: "3"
services:
  db:
    container_name: pg_container
    image:  postgres
    restart: always 
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
       POSTGRES_PASSWORD: pass123
  pgadming:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.root
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"